/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fase2;

/**
 *
 * @author denni
 */
import fase2.entrada;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;
import fase2.Estructura.ArbolB;
import Arbol.ArbolBB;
public class CreateUser extends javax.swing.JFrame {
Carga ca;
    /**
     * Creates new form CreateUser
     */

public ArbolBB arbol;
public long verdpi;
    public CreateUser() {
        initComponents();
        ca=new Carga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        pass2 = new javax.swing.JTextField();
        dpi2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clienteee = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Password");

        jLabel3.setText("DPI");

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });

        pass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass2KeyPressed(evt);
            }
        });

        dpi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dpi2KeyPressed(evt);
            }
        });

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        clienteee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteeeMouseEntered(evt);
            }
        });
        clienteee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteeeActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar Grafica");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Return");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar Y Cargar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpi2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(clienteee, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1)
                                .addGap(40, 40, 40)
                                .addComponent(jButton3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clienteee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dpi2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(94, 94, 94)
                        .addComponent(jButton4)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new fase2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.showOpenDialog(seleccionar);
        String path = seleccionar.getSelectedFile().getAbsolutePath();
        
        ca.carga(path, entrada.arbolb);
        
      entrada.arbolb.Show();
      
        String[] mostrar=entrada.arbolb.combo.split(",");
        
        for (String string : mostrar) {
            
            if (string.equals("null")) {
                
            } else {
                
                clienteee.addItem(string);
            }
            
        }
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (dpi2.getText().equals("") ||  pass2.getText().equals("") || this.nombre.getText().equals("")) {
                 JOptionPane.showMessageDialog(null,"Llenar espacio(s)");
                 
                 
                 
             }else{
             long dpi= Long.parseLong(dpi2.getText());
        String nombre=this.nombre.getText();
        String pass= this.pass2.getText();
             
             if (entrada.arbolb.Contain(dpi)==true) {
                 JOptionPane.showMessageDialog(null,"Ya Existe Usuario Con El DPI Ingresado");
             }{
             
             entrada.arbolb.Insert(dpi, pass, nombre);
             JOptionPane.showMessageDialog(null,"Usuario Creado");
             }
         
        
        
        
         
         }        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        // TODO add your handling code here:
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
             if (dpi2.getText().equals("") ||  pass2.getText().equals("") || this.nombre.getText().equals("")) {
                 JOptionPane.showMessageDialog(null,"Llenar espacio(s)");
                 
                 
                 
             }else{
             long dpi= Long.parseLong(dpi2.getText());
        String nombre=this.nombre.getText();
        String pass= this.pass2.getText();
             
             if (entrada.arbolb.Contain(dpi)==true) {
                 JOptionPane.showMessageDialog(null,"Ya Existe Usuario Con El DPI Ingresado");
             }{
             
             entrada.arbolb.Insert(dpi, pass, nombre);
             JOptionPane.showMessageDialog(null,"Usuario Creado");
             }
        
        
        
         
         }
        }
    }//GEN-LAST:event_nombreKeyPressed

    private void dpi2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpi2KeyPressed
        // TODO add your handling code here:
        
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
             if (dpi2.getText().equals("") ||  pass2.getText().equals("") || this.nombre.getText().equals("")) {
                 JOptionPane.showMessageDialog(null,"Llenar espacio(s)");
                 
                 
                 
             }else{
             long dpi= Long.parseLong(dpi2.getText());
        String nombre=this.nombre.getText();
        String pass= this.pass2.getText();
             
             if (entrada.arbolb.Contain(dpi)==true) {
                 JOptionPane.showMessageDialog(null,"Ya Existe Usuario Con El DPI Ingresado");
             }{
             
             entrada.arbolb.Insert(dpi, pass, nombre);
             JOptionPane.showMessageDialog(null,"Usuario Creado");
             }
         
        
        
        
         
         }
        }
    }//GEN-LAST:event_dpi2KeyPressed

    private void pass2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass2KeyPressed
        // TODO add your handling code here:
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
             if (dpi2.getText().equals("") ||  pass2.getText().equals("") || this.nombre.getText().equals("")) {
                 JOptionPane.showMessageDialog(null,"Llenar espacio(s)");
                 
                 
                 
             }else{
             long dpi= Long.parseLong(dpi2.getText());
        String nombre=this.nombre.getText();
        String pass= this.pass2.getText();
             
             if (entrada.arbolb.Contain(dpi)==true) {
                 JOptionPane.showMessageDialog(null,"Ya Existe Usuario Con El DPI Ingresado");
             }{
             
             entrada.arbolb.Insert(dpi, pass, nombre);
             JOptionPane.showMessageDialog(null,"Usuario Creado");
             }
         
        
        
        
         
         }
        }
    }//GEN-LAST:event_pass2KeyPressed

    private void clienteeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteeeMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_clienteeeMouseClicked

    private void clienteeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteeeMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_clienteeeMouseEntered

    private void clienteeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteeeActionPerformed
        // TODO add your handling code here:
        try {
            String ver=clienteee.getSelectedItem().toString();
        int lo=0;
        String[] ver2=ver.split("-");
      String ver0=ver2[0];
       String ver3=ver2[1];
       
     long ver4= Long.parseLong(ver3);
       
        if (entrada.arbolb.Contain(ver4)) {
            nombre.setText(ver0);
            dpi2.setText(ver3);
            pass2.setText(entrada.arbolb.contra);
            verdpi=Long.parseLong(ver3);
        }
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_clienteeeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        try {
            String jk=dpi2.getText();
        } catch (Exception e) {
        }
        long cambio=Long.parseLong(dpi2.getText());
        if (entrada.arbolb.Contain(verdpi)) {
            
            entrada.arbolb.buscar2(verdpi,cambio, pass2.getText(), nombre.getText());
            clienteee.removeAllItems();
        entrada.arbolb.Show();
      
        String[] mostrar=entrada.arbolb.combo.split(",");
        
        for (String string : mostrar) {
            
            if (string.equals("null")) {
                
            } else {
                
                clienteee.addItem(string);
            }
            
        }
        } else {
            JOptionPane.showMessageDialog(null,"Arreglar el DPI");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            long cambio=Long.parseLong(dpi2.getText());if (entrada.arbolb.Contain(verdpi)) {
            
            entrada.arbolb.Remove(cambio);
            clienteee.removeAllItems();
        entrada.arbolb.Show();
      
        String[] mostrar=entrada.arbolb.combo.split(",");
        
        for (String string : mostrar) {
            
            if (string.equals("null")) {
                
            } else {
                
                clienteee.addItem(string);
            }
            
        }
        } else {
            JOptionPane.showMessageDialog(null,"Arreglar el DPI");
        }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        arbol= new ArbolBB();
         entrada.arbolb.Show();
         long id=0;
         String nombre="";
         String contrasena="";
        String[] mostrar=entrada.arbolb.combo.split(",");
        for (String string : mostrar) {
            String [] hola=string.split("-");
            
                for (String string1 : hola) {
                    if (nombre=="") {
                        nombre=string1;
                    } else if (id==0) {
                        id=Long.parseLong(string1);
                    }
                    else {
                        contrasena=string1;
                    }
                    
                  
            }
                 
        
            
            arbol.insertarDato(id, nombre, contrasena);
            id=0;
            nombre="";
            contrasena="";
        }
        arbol.graphAllTreeB();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clienteee;
    private javax.swing.JTextField dpi2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pass2;
    // End of variables declaration//GEN-END:variables
}
